import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Row,
  Column,
  Text,
} from "@react-email/components";

interface AdminNotificationProps {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  courseCategory: string;
  preferredCourses: string[];
  classType: string;
  classMode: string;
  preferredTime: string;
  goals?: string;
}

export default function AdminNotification({
  firstName,
  lastName,
  email,
  phone,
  courseCategory,
  preferredCourses,
  classType,
  classMode,
  preferredTime,
  goals,
}: AdminNotificationProps) {
  return (
    <Html>
      <Head />
      <Preview>New Student Registration Received</Preview>

      <Body
        style={{
          backgroundColor: "#f5f7fa",
          fontFamily: "Arial, sans-serif",
          padding: "30px 0",
        }}
      >
        <Container
          style={{
            maxWidth: "650px",
            margin: "0 auto",
            backgroundColor: "#ffffff",
            borderRadius: "8px",
            border: "1px solid #e5e7eb",
            padding: "30px",
          }}
        >
          <Heading
            style={{
              color: "#0f172a",
              fontSize: "24px",
              marginBottom: "20px",
            }}
          >
            📩 New Student Registration
          </Heading>

          <Text style={{ color: "#475569", marginBottom: "20px" }}>
            A new student has registered through the Drill Daily website.
          </Text>

          <Section>
            <Row>
              <Column>
                <Text>
                  <strong>Name:</strong> {firstName} {lastName}
                </Text>

                <Text>
                  <strong>Email:</strong> {email}
                </Text>

                <Text>
                  <strong>Phone:</strong> {phone}
                </Text>

                <Text>
                  <strong>Course Category:</strong> {courseCategory}
                </Text>

                <Text>
                  <strong>Preferred Classes:</strong>{" "}
                  {preferredCourses.length > 0
                    ? preferredCourses.join(", ")
                    : "None selected"}
                </Text>

                <Text>
                  <strong>Class Type:</strong> {classType}
                </Text>

                <Text>
                  <strong>Class Mode:</strong> {classMode}
                </Text>

                <Text>
                  <strong>Preferred Time:</strong> {preferredTime}
                </Text>

                <Text>
                  <strong>Goals / Timeline:</strong>{" "}
                  {goals?.trim() || "No goals provided"}
                </Text>
              </Column>
            </Row>
          </Section>

          <Section
            style={{
              marginTop: "30px",
              borderTop: "1px solid #e5e7eb",
              paddingTop: "20px",
            }}
          >
            <Text
              style={{
                fontSize: "13px",
                color: "#64748b",
              }}
            >
              This email was automatically generated by the Drill Daily
              website.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}